const products = [
  {
    id: 1,
    imgUrl: 'https://images.meesho.com/images/products/385302359/ypybm_512.avif?width=360',
    name: 'Men Casual Sneakers',
    description: 'Lightweight sneakers designed for everyday comfort with breathable material and durable sole.',
    rating: 2.4,
    price: 999,
    discountedPrice: 699,
    discountPercentage: 30,
    gender: 'male',
    category: 'casual',
  },
  {
    id: 2,
    imgUrl: 'https://images.meesho.com/images/products/533733490/9pdqd_512.avif?width=360',
    name: 'Women Casual Sneakers',
    description: 'Stylish and comfortable sneakers perfect for daily wear with soft cushioning.',
    rating: 5,
    price: 1099,
    discountedPrice: 769,
    discountPercentage: 30,
    gender: 'female',
    category: 'casual',
  },
  {
    id: 3,
    imgUrl: 'https://images.meesho.com/images/products/153388666/twbal_512.avif?width=360',
    name: 'Men Running Shoes',
    description: 'High-performance running shoes with breathable mesh and strong grip for active lifestyle.',
    rating: 3.6,
    price: 1499,
    discountedPrice: 1049,
    discountPercentage: 30,
    gender: 'male',
    category: 'running',
  },
  {
    id: 4,
    imgUrl: 'https://images.meesho.com/images/products/468404179/k4syn_512.avif?width=360',
    name: 'Women Running Shoes',
    description: 'Lightweight running shoes designed for comfort and flexibility during workouts.',
    rating: 4.3,
    price: 1299,
    discountedPrice: 909,
    discountPercentage: 30,
    gender: 'female',
    category: 'sports',
  },
  {
    id: 5,
    imgUrl: 'https://images.meesho.com/images/products/544531294/5ss59_512.avif?width=360',
    name: 'Men Casual Slip-On Shoes',
    description: 'Easy slip-on casual shoes with breathable fabric and flexible sole.',
    rating: 4.2,
    price: 1199,
    discountedPrice: 839,
    discountPercentage: 30,
    gender: 'male',
    category: 'casual',
  },
  {
    id: 6,
    imgUrl: 'https://images.meesho.com/images/products/547474447/ouphu_512.avif?width=360',
    name: 'Women Casual Slip-On Shoes',
    description: 'Comfortable slip-on shoes perfect for daily wear with lightweight design.',
    rating: 1.4,
    price: 899,
    discountedPrice: 629,
    discountPercentage: 30,
    gender: 'female',
    category: 'casual',
  },
  {
    id: 7,
    imgUrl: 'https://images.meesho.com/images/products/662828965/0wypa_512.avif?width=360',
    name: 'Men Formal Leather Shoes',
    description: 'Premium formal shoes crafted with durable material for office and events.',
    rating: 4.1,
    price: 799,
    discountedPrice: 559,
    discountPercentage: 30,
    gender: 'male',
    category: 'formal',
  },
  {
    id: 8,
    imgUrl: 'https://images.meesho.com/images/products/849566930/pqxsl_512.avif?width=360',
    name: 'Women Casual Walking Shoes',
    description: 'Soft and breathable walking shoes designed for comfort and style.',
    rating: 4.3,
    price: 999,
    discountedPrice: 699,
    discountPercentage: 30,
    gender: 'female',
    category: 'casual',
  },
  {
    id: 9,
    imgUrl: 'https://images.meesho.com/images/products/405357638/0ezlq_512.avif?width=360',
    name: 'Men Sports Shoes',
    description: 'Durable sports shoes with strong grip and cushioning for workouts and outdoor activities.',
    rating: 4.5,
    price: 1399,
    discountedPrice: 979,
    discountPercentage: 30,
    gender: 'male',
    category: 'sports',
  },
  {
    id: 10,
    imgUrl: 'https://images.meesho.com/images/products/790206254/nm8up_512.avif?width=360',
    name: 'Women Sports Shoes',
    description: 'Lightweight sports shoes designed for fitness, running, and daily comfort.',
    rating: 4.2,
    price: 899,
    discountedPrice: 629,
    discountPercentage: 30,
    gender: 'female',
    category: 'sports',
  },
  {
    id: 11,
    imgUrl: 'https://images.meesho.com/images/products/363668967/pqncr_512.avif?width=360',
    name: 'Men Formal Oxford Shoes',
    description: 'Classic Oxford shoes perfect for office wear and formal occasions.',
    rating: 4.4,
    price: 1999,
    discountedPrice: 1399,
    discountPercentage: 30,
    gender: 'male',
    category: 'formal',
  },
  {
    id: 12,
    imgUrl: 'https://images.meesho.com/images/products/475653540/9uxwz_512.avif?width=360',
    name: 'Women Formal Heels',
    description: 'Elegant formal heels designed to provide style and comfort for long hours.',
    rating: 4.6,
    price: 1899,
    discountedPrice: 1329,
    discountPercentage: 30,
    gender: 'female',
    category: 'formal',
  },
  {
    id: 13,
    imgUrl: 'https://images.meesho.com/images/products/801026195/22j87_512.avif?width=360',
    name: 'Men Party Wear Shoes',
    description: 'Stylish shoes designed for parties and special occasions with premium finish.',
    rating: 4.7,
    price: 2499,
    discountedPrice: 1749,
    discountPercentage: 30,
    gender: 'male',
    category: 'casual',
  },
  {
    id: 14,
    imgUrl: 'https://images.meesho.com/images/products/899422117/mp6pb_512.avif?width=360',
    name: 'Women Party Wear Heels',
    description: 'Trendy party heels that add elegance and confidence to your look.',
    rating: 4.5,
    price: 2199,
    discountedPrice: 1539,
    discountPercentage: 30,
    gender: 'female',
    category: 'casual',
  },
  {
    id: 15,
    imgUrl: 'https://images.meesho.com/images/products/504693228/mgnx7_512.avif?width=360',
    name: 'Men Smart Casual Shoes',
    description: 'Versatile shoes combining formal and casual style for everyday wear.',
    rating: 4.1,
    price: 1799,
    discountedPrice: 1259,
    discountPercentage: 30,
    gender: 'male',
    category: 'casual',
  },
  {
    id: 16,
    imgUrl: 'https://images.meesho.com/images/products/899223585/ypbxx_512.avif?width=360',
    name: 'Women Smart Casual Shoes',
    description: 'Comfortable and stylish shoes perfect for daily outings and casual occasions.',
    rating: 4.0,
    price: 1599,
    discountedPrice: 1119,
    discountPercentage: 30,
    gender: 'female',
    category: 'casual',
  },
];

export default products;