const products = [
  {
    id: 1,
    imgUrl:
      'https://images.meesho.com/images/products/385302359/ypybm_512.avif?width=360',
    name: 'Men Solid Black T-Shirt',
    description: 'Premium cotton solid black t-shirt for everyday wear.',
    rating: 2.4,
    price: 999,
    discountedPrice: 699,
    discountPercentage: 30,
    gender: 'male',
    category: 'Casual',
  },
  {
    id: 2,
    imgUrl:
      'https://images.meesho.com/images/products/533733490/9pdqd_512.avif?width=360',
    name: 'Women Graphic Printed T-Shirt',
    description: 'Trendy graphic printed t-shirt with soft fabric.',
    rating: 5,
    price: 1099,
    discountedPrice: 769,
    discountPercentage: 30,
    gender: 'female',
    category: 'Casual',
  },
  {
    id: 3,
    imgUrl:
      'https://images.meesho.com/images/products/153388666/twbal_512.avif?width=360',
    name: 'Men Oversized T-Shirt',
    description: 'Comfortable oversized t-shirt with relaxed fit.',
    rating: 3.6,
    price: 1499,
    discountedPrice: 1049,
    discountPercentage: 30,
    gender: 'male',
    category: 'Semi-Casual',
  },
  {
    id: 4,
    imgUrl:
      'https://images.meesho.com/images/products/468404179/k4syn_512.avif?width=360',
    name: 'Women Polo Neck T-Shirt',
    description: 'Stylish polo neck t-shirt suitable for casual wear.',
    rating: 4.3,
    price: 1299,
    discountedPrice: 909,
    discountPercentage: 30,
    gender: 'female',
    category: 'Semi-Casual',
  },
  {
    id: 5,
    imgUrl:
      'https://images.meesho.com/images/products/544531294/5ss59_512.avif?width=360',
    name: 'Men Striped T-Shirt',
    description: 'Classic striped t-shirt made with breathable fabric.',
    rating: 4.2,
    price: 1199,
    discountedPrice: 839,
    discountPercentage: 30,
    gender: 'male',
    category: 'Casual',
  },
  {
    id: 6,
    imgUrl:
      'https://images.meesho.com/images/products/547474447/ouphu_512.avif?width=360',
    name: 'Women Round Neck Cotton T-Shirt',
    description: 'Soft cotton round neck t-shirt for daily comfort.',
    rating: 1.4,
    price: 899,
    discountedPrice: 629,
    discountPercentage: 30,
    gender: 'female',
    category: 'Casual',
  },
  {
    id: 7,
    imgUrl:
      'https://images.meesho.com/images/products/662828965/0wypa_512.avif?width=360',
    name: 'Men Plain White T-Shirt',
    description: 'Simple and clean white t-shirt with premium finish.',
    rating: 4.1,
    price: 799,
    discountedPrice: 559,
    discountPercentage: 30,
    gender: 'male',
    category: 'Formal',
  },
  {
    id: 8,
    imgUrl:
      'https://images.meesho.com/images/products/849566930/pqxsl_512.avif?width=360',
    name: 'Women Pastel Color T-Shirt',
    description: 'Pastel shade t-shirt with smooth and breathable fabric.',
    rating: 4.3,
    price: 999,
    discountedPrice: 699,
    discountPercentage: 30,
    gender: 'female',
    category: 'Semi-Casual',
  },
  {
    id: 9,
    imgUrl:
      'https://images.meesho.com/images/products/405357638/0ezlq_512.avif?width=360',
    name: 'Men Gym Wear T-Shirt',
    description: 'Moisture-wicking t-shirt perfect for workouts.',
    rating: 4.5,
    price: 1399,
    discountedPrice: 979,
    discountPercentage: 30,
    gender: 'male',
    category: 'Sportswear',
  },
  {
    id: 10,
    imgUrl:
      'https://images.meesho.com/images/products/790206254/nm8up_512.avif?width=360',
    name: 'Women Crop T-Shirt',
    description: 'Stylish crop t-shirt for modern casual look.',
    rating: 4.2,
    price: 899,
    discountedPrice: 629,
    discountPercentage: 30,
    gender: 'female',
    category: 'Party-wear',
  },

  {
    id: 11,
    imgUrl:
      'https://images.meesho.com/images/products/363668967/pqncr_512.avif?width=360',
    name: 'Men Formal Blue Shirt',
    description: 'Elegant formal shirt suitable for office wear.',
    rating: 4.4,
    price: 1999,
    discountedPrice: 1399,
    discountPercentage: 30,
    gender: 'male',
    category: 'Formal',
  },
  {
    id: 12,
    imgUrl:
      'https://images.meesho.com/images/products/475653540/9uxwz_512.avif?width=360',
    name: 'Women Formal White Shirt',
    description: 'Classic white formal shirt with tailored fit.',
    rating: 4.6,
    price: 1899,
    discountedPrice: 1329,
    discountPercentage: 30,
    gender: 'female',
    category: 'Formal',
  },
  {
    id: 13,
    imgUrl:
      'https://images.meesho.com/images/products/801026195/22j87_512.avif?width=360',
    name: 'Men Party Wear Shirt',
    description: 'Stylish party wear shirt with glossy finish.',
    rating: 4.7,
    price: 2499,
    discountedPrice: 1749,
    discountPercentage: 30,
    gender: 'male',
    category: 'Party-wear',
  },
  {
    id: 14,
    imgUrl:
      'https://images.meesho.com/images/products/899422117/mp6pb_512.avif?width=360',
    name: 'Women Party Wear Top',
    description: 'Trendy top designed for evening parties.',
    rating: 4.5,
    price: 2199,
    discountedPrice: 1539,
    discountPercentage: 30,
    gender: 'female',
    category: 'Party-wear',
  },
  {
    id: 15,
    imgUrl:
      'https://images.meesho.com/images/products/504693228/mgnx7_512.avif?width=360',
    name: 'Men Semi Casual Shirt',
    description: 'Perfect balance between formal and casual style.',
    rating: 4.1,
    price: 1799,
    discountedPrice: 1259,
    discountPercentage: 30,
    gender: 'male',
    category: 'Semi-Casual',
  },
  {
    id: 16,
    imgUrl:
      'https://images.meesho.com/images/products/899223585/ypbxx_512.avif?width=360',
    name: 'Women Semi Casual Top',
    description: 'Comfortable semi-casual top for daily outings.',
    rating: 4.0,
    price: 1599,
    discountedPrice: 1119,
    discountPercentage: 30,
    gender: 'female',
    category: 'Semi-Casual',
  },
];

export default products;
// Only one variable or function can undergo a default
